name: Python Linting and Dependency Management

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        poetry install

    - name: Lint with PyLint
      run: |
        source env/bin/activate
        poetry run pylint src
